
input : seurat.h5seurat  #输入的 seurat 文件
updata: False  # 是否覆盖原文件 False 则在输出目录生成注释后的seurat
output: newcelltype  # 结果输出目录
Modified_file: newcelltype.tsv   # 用来修改细胞类型的文件
Modified_col: clusters  #  用来修改的列
reduct: umap  # 降维方法
updata_bynewcelltype: True  # 是否更新后续基于 newcelltype的分析 包含 cor vis marker 分析
newseurat: newcelltype/seurat.h5seurat  # 更新细胞类型后 新细胞类型的列
type_name: new_celltype  # 
species: mouse  # 物种 
run: modified_cell_type  # 这个不要改
