# 物种信息配置文件
# 新增可直接复制该模板
# species:
#   anno: 
#   KEGG:
#   GO_BP:
#   Hallmakr: 


human:
  anno: /data/database/cellranger-refdata/refdata-gex-GRCh38-2020-A/ 
  KEGG: /data/database/GSEA_gmt/human/v2023/c2.cp.kegg.v2023.1.Hs.symbols.gmt
  GO_BP: /data/database/GSEA_gmt/human/v2023/c5.go.bp.v2023.1.Hs.symbols.gmt
  Hallmakr: /gpfs/oe-scrna/zhengfuxing/Publc/h.all.v2023.1.Hs.symbols.gmt


mouse:
  anno: /data/database/cellranger-refdata/refdata-gex-mm10-2020-A/
  KEGG: /data/database/GSEA_gmt/mouse/gene_kegg.gmt
  GO_BP: /data/database/GSEA_gmt/mouse/v2023/m5.go.bp.v2023.1.Mm.symbols.gmt
  Hallmakr: /gpfs/oe-scrna/zhengfuxing/Publc/mh.all.v2023.1.Mm.symbols.gmt


rat:
  anno: "/data/database/cellranger-refdata/refdata-mRatBN7/"
  KEGG: "/data/database/GSEA_gmt/rat/gene_kegg.gmt"
  GO_BP: /data/database/GSEA_gmt/rat/gene_go_bp.backgroud.gmt
  Hallmakr: "unknown"